---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r data}

w.d <- "C:/Users/noahp/Box/Research/pools-projects"
source(paste0(w.d, "/code/load_packages.R"))
library(readxl)
library(tidyverse)
library(naniar)
w.d <- "C:/Users/noahp/Box/Research/pools-projects"
data <- readxl::read_xlsx(paste0(w.d,"/data/data-2020-11-04/POOLS_data_2020-11-04-clean.xlsx"))
#data[-c(1:3,62),]<- apply(data[-c(1:3,62),],2, function(x){x-3})

naniar::vis_miss(data)

```


Next, look at the summary level statistics of the data.


```{r summary}

data %>%
  summarise(
    N = n()
  )

apply(data[-1,],2, summary)

```



```{r item-analysis}

library(psychometric)

psychometric::item.exam(data[,5:61],discrim = T)


library(psych)
fit.item <- psych::alpha(x = data[,5:61])
fit.item

```


Impute missing values

```{r impute-median}

data.imp <- data[,5:61]
anyNA(data.imp)
i <- 1
for(i in 1:ncol(data.imp)){
  
  i.med <- median(data.imp[,i, drop=T], na.rm=T)
  data.imp[,i] <- ifelse(is.na(data.imp[,i, drop=T]),
                         i.med, data.imp[,i, drop=T])
}
anyNA(data.imp)

```


```{r cor}

cor.dat <- cor(data.imp)

kable(cor.dat, format="html", digits=3) %>%
  kable_styling(full_width = T) %>%
  scroll_box()

library(ggplot2)
library(ggcorrplot)
ggcorrplot(cor.dat, 
           hc.order = TRUE, 
           type = "lower")



library(qgraph)

pools.grp <- list(
  g1 = c(1:19),
  g2 = c(20:31),
  g3 = c(32:42),
  g4 = c(43:57)
)
qgraph(cor.dat,groups=pools.grp,
       minimum=0.25,
       legend=TRUE)


data(big5)
data(big5groups)
qgraph(cor(big5),minimum=0.25,cut=0.4,vsize=2,groups=big5groups,legend=TRUE,borders=FALSE)
title("Big 5 correlations",line=-2,cex.main=2)

```

```{r fa-1}

fit.fa1 <- psych::fa(
  r = data[,5:61],covar = T, impute = "median",
  nfactors = 1,fm = "pa", rotate = "promax"
)
fit.fa1

```


