---
title: "POOLS Development: CFA Invariance Testing"
author: "R. Noah Padgett, Shan Jiang, Laura Shero, & Todd Kettlers"
date: "2020-11-16"
output:
  workflowr::wflow_html:
    toc: true
    code_folding: show
---

# Data

```{r data}

source("code/load_packages.R")

mydata1 <- read.table("data/data-2020-11-16/pools_data_split1_2020_11_16.txt", sep="\t", header=T)
mydata2 <- read.table("data/data-2020-11-16/pools_data_split2_2020_11_16.txt", sep="\t", header=T)
mydata <- full_join(mydata1, mydata2)
# transform responses to (-2, 2) scale
mydata[, 7:63] <- apply(mydata[,7:63], 2, function(x){x-3})
mydata$teach <- factor(mydata$teach, levels=c(1, 2), labels=c("No to Online Teaching Experience", "Yes to Online Teaching Experience"))
```

## Data Summary

```{r data-sum}

use.var <- c(paste0("Q4_",c(3:5,9, 11, 15, 18)), #13
             paste0("Q5_",c(1:3,5:6, 12)), #8-> 14- 21
             paste0("Q6_",c(2, 5:8, 11)), #9 -> 22-30
             paste0("Q7_",c(2, 4:5, 7:8, 14))) #31-38

psych::describe(
  mydata[, use.var]
)

psych::describeBy(
  mydata[, use.var],group = mydata$teach
)

```


# CFA

The hypothesized four-factor solution is shown below.


The above model can be convert to code using the below model.

```{r}

mod1 <- "
EL =~ Q4_3 + Q4_4 + Q4_5 + Q4_9 + Q4_11 + Q4_15 + Q4_18
SC =~ Q5_1 + Q5_2 + Q5_3 + Q5_5 + Q5_6 + Q5_12
IN =~ Q6_2 + Q6_5 + Q6_6 + Q6_7 + Q6_8 + Q6_11
EN =~ Q7_2 + Q7_4 + Q7_5 + Q7_7 + Q7_8 + Q7_14

EL ~~ EL + SC + IN + EN
SC ~~ SC + IN + EN
IN ~~ IN + EN
EN ~~ EN

Q4_3 ~~ Q4_4
Q5_5 + Q5_2 ~~ Q5_6
Q6_2 ~~ Q6_8
Q7_7 ~~ Q7_8
"

fit0 <- lavaan::cfa(mod1, data=mydata, estimator = "MLM",group = "teach")
summary(fit0, standardized=T, fit.measures=T)

```


```{r}

library(semTools)


## fit indices of interest for multiparameter omnibus test
myAFIs <- c("chisq","cfi","rmsea","srmr","aic", "bic")

## Use only 20 permutations for a demo.  In practice,
## use > 1000 to reduce sampling variability of estimated p values

## test configural invariance
set.seed(12345)
out.config <- permuteMeasEq(nPermute = 1000, con = fit0,AFIs = myAFIs)
summary(out.config)

hist(out.config, AFI = "chisq", nd = 2, alpha = .01,
     legendArgs = list(x = "top"))
hist(out.config, AFI = "cfi", legendArgs = list(x = "topright"))



```

