---
title: "Pilot Study: Confirmatory Factor Analysis"
author: "R. Noah Padgett"
date: "2020-11-16"
output: html_document
---

# Data

```{r data}

source("code/load_packages.R")

mydata <- read.table("data/data-2020-11-16/pools_data_split2_2020_11_16.txt", sep="\t", header=T)


# transform responses to (-2, 2) scale
mydata[, 7:63] <- apply(mydata[,7:63], 2, function(x){x-3})

```

## Data Summary

```{r data-sum}

psych::describe(
  mydata[, c(paste0("Q4_",c(1:5,8:11, 15:19)),
             paste0("Q5_",c(1:6, 8, 12)),
             paste0("Q6_",c(1:8, 11)),
             paste0("Q7_",c(2, 4:5, 7:8, 12:14)))]
)

```


# CFA

## Model 1

### Maximum Likelihood

```{r mle1}

mod1 <- "
EL =~ Q4_1 + Q4_2 + Q4_3 + Q4_4 + Q4_5 + Q4_8 + Q4_9 + Q4_10 + Q4_11 + Q4_15 + Q4_16 + Q4_17 + Q4_18 + Q4_19
SC =~ Q5_1 + Q5_2 + Q5_3 + Q5_4 + Q5_5 + Q5_6 + Q5_8 + Q5_12
IN =~ Q6_1 + Q6_2 + Q6_3 + Q6_4 + Q6_5 + Q6_6 + Q6_7 + Q6_8 + Q6_11
EN =~ Q7_2 + Q7_4 + Q7_5 + Q7_7 + Q7_8 + Q7_12 + Q7_13 + Q7_14

EL ~~ EL + SC + IN + EN
SC ~~ SC + IN + EN
IN ~~ IN + EN
EN ~~ EN
"

fit1 <- lavaan::cfa(mod1, data=mydata)
summary(fit1, standardized=T, fit.measures=T)

```


### DWLS

```{r}

fit1 <- lavaan::cfa(mod1, data=mydata, ordered=T)
summary(fit1, standardized=T, fit.measures=T)

```


### MIIV

```{r}

# get the model implied instrumental variables
miivs(mod1)


fit1 <- MIIVsem::miive(mod1, data=mydata)
summary(fit1)

```

### MIIV Categorical

```{r miiv-cat}

fit1 <- MIIVsem::miive(
  mod1, data=mydata,
  ordered=c(
    paste0("Q4_",c(1:5,8:11, 15:19)),
    paste0("Q5_",c(1:6, 8, 12)),
    paste0("Q6_",c(1:8, 11)),
    paste0("Q7_",c(2, 4:5, 7:8, 12:14))
  )
)
summary(fit1)

```




